#!/usr/bin/env bash
#
# Codemagic pre-build step for this repo.
#
# The android/ folder IS committed (same approach as the qr_scanner app), so
# normally this script just fetches packages and refreshes the launcher icon.
# ios/ is NOT committed, so for the iOS workflow it runs `flutter create` to
# materialise ios/ first.
#
# How to wire it up:
#   * Codemagic UI (Workflow Editor):  paste  `bash scripts/codemagic_pre_build.sh`
#     into  Workflow > Build > "Pre-build script".
#   * codemagic.yaml:  already calls this script.
#
# Env:
#   PLATFORMS   comma list of platforms that must exist (default "android").
#               The iOS workflow passes "ios".
#
# Safe to run repeatedly.

set -euo pipefail

ORG="com.oshomeditation"
PROJECT_NAME="osho_meditation"
PLATFORMS="${PLATFORMS:-android}"

# Create any requested native folder that isn't already in the repo.
missing=""
IFS=',' read -ra want <<< "$PLATFORMS"
for p in "${want[@]}"; do
  [ -d "$p" ] || missing="${missing:+$missing,}$p"
done

if [ -n "$missing" ]; then
  echo "==> flutter create (missing: $missing)"
  flutter create \
    --org "$ORG" \
    --project-name "$PROJECT_NAME" \
    --platforms="$missing" \
    .
  for p in "${want[@]}"; do
    test -d "$p" || { echo "ERROR: $p/ was not generated by flutter create"; exit 1; }
  done
else
  echo "==> native folders already present: $PLATFORMS"
fi

echo "==> flutter pub get"
flutter pub get

# Refresh the Android launcher icon from assets/branding/. Idempotent: it just
# rewrites the same PNGs that are already committed under android/.
if [[ ",$PLATFORMS," == *",android,"* ]] || [ -d android ]; then
  echo "==> flutter_launcher_icons"
  dart run flutter_launcher_icons
fi

echo "==> pre-build done"
